### ISSUE TITLE
Ability to hide USD column (or some other column)

### ISSUE THREAD

**Issue by Zettt** [codesonzh/poloniex-ninja#1]
I find the USD value column rather useless. As it takes up screen estate, I'd love to be able to tell the ninja to hide it. Is there a hidde setting or something to make it go away?

**Comment by codesonzh** [comment]
Good feature request. :-) 

I think this is worth doing, I'll get around to it some time in the next few days.

Thanks & cheers!

**Comment by codesonzh** [comment]
Feature request implemented [546321cfb43c0be4abc3ae2b9225c116c3f8dbcb](https://github.com/codesonzh/poloniex-ninja/commit/546321cfb43c0be4abc3ae2b9225c116c3f8dbcb).

Thanks, @Zettt for the suggestion. The chrome extension updates are in progress, will tweet. :)
