### ISSUE TITLE
N/A in every cell in every row, with error codes this time

### ISSUE THREAD

**Issue by zoonosis** [codesonzh/poloniex-ninja#12]
Same issue as before but I did the Ctrl Shift I like you asked and got this
![image](https://user-images.githubusercontent.com/30029223/28343989-205dea1a-6c64-11e7-8877-bf3f2fbca220.png)

**Comment by zoonosis** [comment]
The only difference I can find is that I just did a withdrawl of some bitcoin today, it was working fine before that. Not sure if that would make a difference or not.

**Comment by codesonzh** [comment]
Same as #9, the extension is working fine, but the browser is unable to connect to Poloniex in all channels. It's a server-side capacity issue, Poloniex is known to have scaling issues and spikes all around.
