### ISSUE TITLE
N/A in every cell in every row

### ISSUE THREAD

**Issue by pookNast** [codesonzh/poloniex-ninja#15]
![image](https://user-images.githubusercontent.com/14242552/28972115-73e6ae02-78fc-11e7-83e2-0c4111d43249.png)
Getting similar errors as to issue #9 and #12.
I have posted the screen shot of the console output. Is there anything I can do to remedy this?

**Comment by pookNast** [comment]
It auto magically started working again. But would like some insight as to why this happens. Has occurred multiple times over the past couple of weeks. Cheers.

**Comment by codesonzh** [comment]
Hi, thanks for reporting, but this issue has nothing to do with the extension itself. Please take a look at #9 and #12. The best that could be done is to just repeatedly try and make a connection, but if Poloniex is flaky on it's own, doing so would only make things worse.

**Comment by codesonzh** [comment]
Interesting that you chose the same name as #9, btw :-D
