### ISSUE TITLE
+Infinity and n/a in table.

### ISSUE THREAD

**Issue by Zettt** [codesonzh/poloniex-ninja#2]
Good morning.

Here's a new issue. The table shows `+Infinity` for coins that have been deposited, or are not possible to withdraw (like SC).

![](https://cl.ly/2W3c3E183h0i/Screen%20Shot%202017-06-07%20at%2022.54.01.png)

**Comment by codesonzh** [comment]
Deposits and withdrawals are now also taken into account. Get version 0.0.31.  I'll close up this one for now.

**Comment by Zettt** [comment]
@codesonzh Works as intended. Thanks!
