### ISSUE TITLE
Firefox or Brave plugin

### ISSUE THREAD

**Issue by criptonauta** [codesonzh/poloniex-ninja#8]
Hi!
I love Polo Ninja and hate Chrome.

I know it's better for many things, but still... do you have plans for a Firefox or Brave version?

Best regards

**Comment by codesonzh** [comment]
Hi, at this point I have no plans on expanding to other browsers, however I welcome others to contribute code to allow such cross-platform support.

I'm watching closely as to see how acceptance grows. So far donations have been quite slow. :-(
